# Preface {.unnumbered}

This online textbook is based on my notes from a series of lectures given for a few years at the Aristotle University of Thessaloniki.

This textbook can be used as support material for lectures on basic statistics using R at any level from beginner to advanced. I have paid particular attention to the form of the book, which I think should aid understanding the most common statistical tests using base R and pipe-friendly functions, coherent with the 'tidyverse' design philosophy. It can also be used as a support for self-teaching.


::: {.callout-important appearance="simple"}
This textbook assumes that the reader has a basic knowledge of R. If you want to familiarize yourself with this programming language, we recommend the books below:

- [R for Data Science](https://r4ds.had.co.nz/)
- [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/)
:::


All sections of this textbook are reproducible as they were made using [Quarto](https://quarto.org/)^®^ which is an open-source scientific and technical publishing system built on [Pandoc](https://pandoc.org/).

To learn more about Quarto books visit <https://quarto.org/docs/books>.

## License

This textbook is **free to use**, and is licensed under the [Creative Commons Attribution-NonCommercial-NoDerivs 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) License.
